modLoader="javafml"
loaderVersion="[40,41)"
license="MIT"

[[mods]]
modId="firefearmod"
version="1.0"
displayName="Fear of Fire Mod"
authors="Sylsatra"
description='''A mod to make mobs scared of fire.'''

[[dependencies.fearofire]]
modId="forge"
mandatory=true
versionRange="[40,)" 
ordering="NONE"
side="BOTH"

[[dependencies.fearofire]]
modId="minecraft"
mandatory=true
versionRange="[1.18,1.19)" 
ordering="NONE"
side="BOTH"
