modLoader="javafml"
loaderVersion="[47,)"
license="GPL-3.0-only"

[[mods]]
modId="firefearmod"
version="4.1.3"
displayName="Fear of Fire Mod"
authors="Sylsatra"
description='''A mod to make mobs scared of fire.'''

[[dependencies.firefearmod]]
modId="forge"
mandatory=true
versionRange="[47.4.0,)" 
ordering="NONE"
side="BOTH"

[[dependencies.firefearmod]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2)" 
ordering="NONE"
side="BOTH"

[[dependencies.firefearmod]]
modId="soundattract"
mandatory=false
versionRange="[4.4.2,)"
ordering="AFTER"
side="BOTH"
