modLoader="javafml"
loaderVersion="[40,)"
license="GPL-3.0-only"

[[mods]]
modId="firefearmod"
version="2.0.1"
displayName="Fear of Fire Mod"
authors="Sylsatra"
description='''A mod to make mobs scared of fire.'''

[[dependencies.firefearmod]]
modId="forge"
mandatory=true
versionRange="[40.3.0,)" 
ordering="NONE"
side="BOTH"

[[dependencies.firefearmod]]
modId="minecraft"
mandatory=true
versionRange="(1.18.1,1.18.2]" 
ordering="NONE"
side="BOTH"
